### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by jdantonio** [jdantonio/didit-cli-client#1]
* [ ] Setup as a gem project
* [ ] Move core logic to lib
* [ ] Move CLI logic to bin
* [ ] Convert to `OptionParser `
* [ ] Setup rspec and webmock
  - [ ] Write unit tests
* [ ] Setup cucumber and aruba
  - [ ] Write integration tests
* [ ] Create Rake task for building gem
* [ ] ConfigureTravis CI
* [ ] Update README
* [ ] Submit PR
